app1/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),  # Página de inicio
    path('curso_list/', views.CursoListView.as_view(), name='curso_list'),
    path('curso_create/', views.CursoCreateView.as_view(), name='curso_create'),
    path('entregables/', views.EntregableListView.as_view(), name='lista_entregables'),
    path('profesores/', views.ProfesorListView.as_view(), name='lista_profesores'),
    path('alumnos/', views.EstudianteListView.as_view(), name='lista_alumnos'),
    path('entregable/create/', views.EntregableCreateView.as_view(), name='entregable-create'),
    path('profesor/create/', views.ProfesorCreateView.as_view(), name='profesor-create'),
    path('estudiante/create/', views.EstudianteCreateView.as_view(), name='estudiante-create'),
    path('buscar-por-nombre/', views.CursoSearchView.as_view(), name='buscar_cursos_por_nombre'),
    path('curso_update/<int:pk>/', views.CursoUpdateView.as_view(), name='curso_update'),
    path('curso_delete/<int:pk>/', views.CursoDeleteView.as_view(), name='curso_delete'),
    path('post_list/', views.PostListView.as_view(), name='post_list'),
    path('create/', views.PostCreateView.as_view(), name='create_post'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update_post'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete_post'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
]

proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/', include(('app1.urls', 'app1'), namespace='app1')),
    
]

app1/models.py
from django.db import models

# Create your models here.

class Curso(models.Model):
    nombre = models.CharField(max_length=100)
    numero_comision = models.IntegerField()

class Estudiante(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)

class Profesor(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    email = models.EmailField(default='correo@example.com')
    profesion = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Entregable(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

app1/forms.py
from django import forms
from .models import Entregable, Profesor, Estudiante, Post
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class EntregableForm(forms.ModelForm):
    class Meta:
        model = Entregable
        fields = '__all__'

class ProfesorForm(forms.ModelForm):
    class Meta:
        model = Profesor
        fields = '__all__'

class EstudianteForm(forms.ModelForm):
    class Meta:
        model = Estudiante
        fields = '__all__'

class CursoSearchForm(forms.Form):
    nombre = forms.CharField(required=False)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields 

app1/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from .models import Curso, Entregable, Profesor, Estudiante, Post
from .forms import EntregableForm, ProfesorForm, EstudianteForm, CursoSearchForm, PostForm, CustomUserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    return render(request, 'index.html')

# Vistas para el modelo Curso
class CursoListView(ListView):
    model = Curso
    template_name = 'curso_list.html'
    context_object_name = 'cursos'

class CursoCreateView(CreateView):
    model = Curso
    fields = ['nombre', 'numero_comision']
    template_name = 'curso_create.html'
    success_url = reverse_lazy('app1:curso_list')

# Vistas para el modelo Entregable
class EntregableCreateView(CreateView):
    model = Entregable
    form_class = EntregableForm
    template_name = 'entregable_form.html'
    success_url = reverse_lazy('app1:index')

class EntregableListView(ListView):
    model = Entregable
    template_name = 'entregable_list.html'
    context_object_name = 'entregables'

# Vistas para el modelo Profesor
class ProfesorCreateView(CreateView):
    model = Profesor
    form_class = ProfesorForm
    template_name = 'profesor_form.html'
    success_url = reverse_lazy('app1:index')

class ProfesorListView(ListView):
    model = Profesor
    template_name = 'profesor_list.html'
    context_object_name = 'profesores'

# Vistas para el modelo Estudiante
class EstudianteCreateView(CreateView):
    model = Estudiante
    form_class = EstudianteForm
    template_name = 'estudiante_form.html'
    success_url = reverse_lazy('app1:index')

class EstudianteListView(ListView):
    model = Estudiante
    template_name = 'estudiante_list.html'
    context_object_name = 'estudiantes'

# Vista para buscar cursos por nombre
class CursoSearchView(FormView):
    template_name = 'buscar_cursos.html'
    form_class = CursoSearchForm

    def form_valid(self, form):
        nombre = form.cleaned_data['nombre']
        cursos = Curso.objects.filter(nombre__icontains=nombre)
        return self.render_to_response({'form': form, 'cursos': cursos})

# Vistas para el modelo Curso
class CursoUpdateView(UpdateView):
    model = Curso
    fields = ['nombre', 'numero_comision']
    template_name = 'curso_update.html'
    success_url = reverse_lazy('app1:curso_list')

class CursoDeleteView(DeleteView):
    model = Curso
    template_name = 'curso_confirm_delete.html'
    success_url = reverse_lazy('app1:curso_list')

class PostListView(ListView):
    model = Post
    template_name = 'post_list.html'
    context_object_name = 'posts'

class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'create_post.html'
    success_url = reverse_lazy('app1:post_list')

class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'update_post.html'
    success_url = reverse_lazy('app1:post_list')

class PostDeleteView(DeleteView):
    model = Post
    template_name = 'delete_post.html'
    success_url = reverse_lazy('app1:post_list')

class RegisterView(CreateView):
    template_name = 'register.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('app1:login')

class CustomLoginView(LoginView):
    template_name = 'login.html'
    
    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.user.is_authenticated:
            return redirect('app1:index')  
        return response

class CustomLogoutView(LogoutView):
    next_page = 'app1:login'

app1/templates/buscar_cursos.html
{% extends 'index.html' %}

{% block content %}
    <div class="container">
        <h1 class="mb-4">Buscar Cursos por Nombre</h1>
        <form method="get" action="">
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Buscar</button>
        </form>
        
        {% if cursos %}
        <h2 class="mt-4">Resultados de la búsqueda:</h2>
        <ul class="list-group">
            {% for curso in cursos %}
            <li class="list-group-item">
                {{ curso.nombre }} - Comisión {{ curso.numero_comision }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
{% endblock %}

app1/templates/create_post.html
{% extends 'index.html' %}

{% block content %}
  <h1>Crear un Nuevo Post</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
  </form>
{% endblock %}

app1/templates/curso_create.html
{% extends 'index.html' %}

{% block content %}
    <div class="container">
        <h1 class="mb-4">Crear un Nuevo Curso</h1>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="nombre" class="form-label">Nombre del Curso:</label>
                <input type="text" name="nombre" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="numero_comision" class="form-label">Número de Comisión:</label>
                <input type="text" name="numero_comision" class="form-control" required>
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
{% endblock %}

app1/templates/curso_list.html
{% extends 'index.html' %}

{% block content %}
    <div class="container">
        <h1 class="mb-4">Lista de Cursos</h1>
        <ul class="list-group">
            {% for c in cursos %}
                <li class="list-group-item">
                    <h4>{{ c.nombre }}</h4>
                    <p>Comision: {{ c.numero_comision }}</p>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

app1/templates/delete_post.html
{% extends 'index.html' %}

{% block content %}
  <h1>Eliminar Post</h1>
  <p>¿Estás seguro de que deseas eliminar el post "{{ post.title }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Eliminar</button>
  </form>
{% endblock %}

app1/templates/entregable_list.html
{% extends 'index.html' %}

{% block content %}
    <div class="container">
        <h1 class="mb-4">Lista de Entregables</h1>
        <ul class="list-group">
            {% for entregable in entregables %}
                <li class="list-group-item">
                    <h4>{{ entregable.nombre }}</h4>
                    <p>{{ entregable.descripcion }}</p>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

app1/templates/estudiante_form.html
{% extends 'index.html' %}

{% block content %}
    <div class="container">
        <h1 class="mb-4">Crear un Nuevo Estudiante</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
{% endblock %}

app1/templates/estudiante_list.html
{% extends 'index.html' %}

{% block content %}
    <div class="container">
        <h1 class="mb-4">Lista de Estudiantes</h1>
        <ul class="list-group">
            {% for e in estudiantes %}
                <li class="list-group-item">
                    {{ e.nombre }} {{ e.apellido }}
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

app1/templates/login.html
{% extends 'index.html' %}

{% block content %}
  <h2>Iniciar Sesión</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Iniciar Sesión</button>
  </form>
  <a href="{% url 'app1:register' %}">¿No tienes una cuenta? Regístrate aquí.</a>
{% endblock %}

app1/templates/logout.html
{% extends 'index.html' %}

{% block content %}
  <h2>Cerrar Sesión</h2>
  <p>Has cerrado sesión exitosamente.</p>
  <a href="{% url 'app1:login' %}">Iniciar sesión nuevamente</a>
{% endblock %}

app1/templates/post_list.html
{% extends 'index.html' %}

{% block content %}
  <h1>Lista de Posts</h1>
  <ul class="list-group">
    {% for post in posts %}
      <li class="list-group-item">
        <div class="d-flex justify-content-between align-items-center">
          <a href="{% url 'app1:update_post' post.pk %}">{{ post.title }}</a>
          <div>
            <a href="{% url 'app1:delete_post' post.pk %}" class="btn btn-danger btn-sm ml-2">Eliminar</a>
          </div>
        </div>
      </li>
    {% endfor %}
  </ul>
  <a href="{% url 'app1:create_post' %}" class="btn btn-primary mt-3">Crear nuevo post</a>
{% endblock %}

app1/templates/profesor_form.html
{% extends 'index.html' %}

{% block content %}
    <div class="container">
        <h1 class="mb-4">Crear un Nuevo Profesor</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
{% endblock %}

app1/templates/profesor_list.html
{% extends 'index.html' %}

{% block content %}
    <div class="container">
        <h1 class="mb-4">Lista de Profesores</h1>
        <ul class="list-group">
            {% for profesor in profesores %}
                <li class="list-group-item">
                    {{ profesor.nombre }} {{ profesor.apellido }}
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}